"""initial schema

Revision ID: 8f124a68339b
Revises: 
Create Date: 2026-06-17 21:38:48.797913
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8f124a68339b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_study_id', 'audit_events', ['study_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_keys'))
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state in ('queued','running','succeeded','failed','cancelled')", name=op.f('ck_job_runs_state_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    op.create_table('ontology_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_snapshots')),
    sa.UniqueConstraint('label', name=op.f('uq_ontology_snapshots_label'))
    )
    op.create_table('schema_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schema_versions')),
    sa.UniqueConstraint('label', name=op.f('uq_schema_versions_label'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('viewer','curator','admin')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scope in ('read','write')", name=op.f('ck_api_tokens_scope_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_tokens_token_hash'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_jti', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('refresh_jti', name=op.f('uq_sessions_refresh_jti'))
    )
    op.create_table('studies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('schema_version_id', sa.Integer(), nullable=True),
    sa.Column('ontology_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['ontology_snapshot_id'], ['ontology_snapshots.id'], name=op.f('fk_studies_ontology_snapshot_id_ontology_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_studies_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_versions.id'], name=op.f('fk_studies_schema_version_id_schema_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studies'))
    )
    op.create_table('mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=False),
    sa.Column('raw_column', sa.Text(), nullable=False),
    sa.Column('matched_field', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('curator_field', sa.Text(), nullable=True),
    sa.Column('curator_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("status in ('pending','accepted','rejected','new_field')", name=op.f('ck_mappings_status_valid')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_mappings_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_mappings_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mappings'))
    )
    op.create_index('ix_mappings_study_id', 'mappings', ['study_id'], unique=False)
    op.create_table('ontology_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('ontology_term', sa.Text(), nullable=True),
    sa.Column('ontology_id', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('curator_term', sa.Text(), nullable=True),
    sa.Column('curator_id', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_ontology_mappings_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_ontology_mappings_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_mappings'))
    )
    op.create_index('ix_ontology_mappings_study_id', 'ontology_mappings', ['study_id'], unique=False)
    op.create_table('mapping_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_mapping_versions_changed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mapping_id'], ['mappings.id'], name=op.f('fk_mapping_versions_mapping_id_mappings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mapping_versions')),
    sa.UniqueConstraint('mapping_id', 'version', name='mapping_version_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapping_versions')
    op.drop_index('ix_ontology_mappings_study_id', table_name='ontology_mappings')
    op.drop_table('ontology_mappings')
    op.drop_index('ix_mappings_study_id', table_name='mappings')
    op.drop_table('mappings')
    op.drop_table('studies')
    op.drop_table('sessions')
    op.drop_table('api_tokens')
    op.drop_table('users')
    op.drop_table('schema_versions')
    op.drop_table('ontology_snapshots')
    op.drop_table('job_runs')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_audit_events_study_id', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
